# Generated by Django 4.2.1 on 2023-06-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(max_length=255)),
                ('tracking_number', models.CharField(max_length=255)),
                ('delivery_date', models.DateField()),
            ],
        ),
    ]
