# Generated by Django 4.2.1 on 2023-06-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.PositiveBigIntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField()),
            ],
        ),
    ]
